version: '3.4'

services:
  dockercreatereactapp:
    image: dockercreatereactapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
